---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(viridis)
```

Before we kept Manhattan, based on room type based on 5 stars, but now do
user dependent subsetting of the dataset

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(borough = neighbourhood_group) %>% 
  select(borough, neighbourhood, stars, price, room_type, lat, long) %>% 
  drop_na(stars)
```


Column {.sidebar}
-----------------------------------------------------------------------

Getting inputs (in the side bar)

```{r}
borough_choices = 
  nyc_airbnb %>%  
  distinct(borough) %>% 
  pull(borough)

selectInput(
  inputId = "borough_choice", 
  label = h3("Select Borough"), #what the user is going to see
  choices = borough_choices,
  selected = "Manhattan"
)
```

Adding another input (slider)

```{r}
min_price = nyc_airbnb %>% 
  pull(price) %>% 
  min()

sliderInput(
  inputId = "price_range", #price_range is the variable name that i've assigned to this slider 
  label = h3("Select Price Range"),
  min = min_price, 
  max = 1000, 
  value = c(100, 400) #two sided sliders
)
```


```{r}
room_choices = 
  nyc_airbnb %>% 
  distinct(room_type) %>% 
  pull

radioButtons(
  inputId = "room_choice", #this is the user defined variable, did not call room type since that is the same name as the column, will get confused need to define that this is what the user is choosing
  label = h3("Select Room Type"),
  choices = room_choices,
  selected = "Entire home/apt"
)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

Create a plotly plot and have it update as per the user choice

```{r}
renderPlotly(
  nyc_airbnb %>% 
  filter(
    borough == input[["borough_choice"]], 
    price %in% input[["price_range"]][1]:input[["price_range"]][2],
    room_type == input[["room_choice"]]) %>% 
  plot_ly(x= ~long, y=~ lat, type = "scatter", mode = "markers", alpha = 0.5, color = ~price)
)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly(
  nyc_airbnb %>% 
    filter(
      borough == input[["borough_choice"]],
      room_type == input[["room_choice"]]
    ) %>% 
    count(neighbourhood) %>% 
    mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
    plot_ly(x = ~neighbourhood, y = ~n, type = "bar")
)
```

### Chart C

```{r}
renderPlotly(
  nyc_airbnb %>% 
    filter(borough == input[["borough_choice"]], 
    price %in% input[["price_range"]][1]:input[["price_range"]][2],
    room_type == input[["room_choice"]]) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(x = ~neighbourhood, y = ~price, type = "box")
)
```

